name: Publish packages

on:
  push:
    tags: ["*"]

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  # GitHub Release (可选，用于创建 Release)
  github:
    uses: tree-sitter/workflows/.github/workflows/release.yml@main
    with:
      generate: true
      attestations: true
  
  # 只发布到 PyPI
  pypi:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    environment:
      name: pypi
      url: https://pypi.org/p/tree-sitter-arkts-open
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.2

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: cp310-* cp311-* cp312-*
          CIBW_SKIP: "*-musllinux_*"
          CIBW_ARCHS_LINUX: x86_64
          CIBW_ARCHS_MACOS: x86_64 arm64
          CIBW_ARCHS_WINDOWS: AMD64

      - name: Build source distribution
        if: matrix.os == 'ubuntu-latest'
        run: |
          python -m pip install build
          python -m build --sdist --outdir wheelhouse

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: wheelhouse/
  
  # NPM 发布 (暂时禁用)
  # npm:
  #   uses: tree-sitter/workflows/.github/workflows/package-npm.yml@main
  #   secrets:
  #     NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  #   with:
  #     generate: true
  
  # Crates.io 发布 (暂时禁用)
  # crates:
  #   uses: tree-sitter/workflows/.github/workflows/package-crates.yml@main
  #   secrets:
  #     CARGO_REGISTRY_TOKEN: ${{secrets.CARGO_REGISTRY_TOKEN}}
  #   with:
  #     generate: true
