name: Publish packages

on:
  push:
    tags: ["*"]

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  # GitHub Release (可选，用于创建 Release)
  github:
    uses: tree-sitter/workflows/.github/workflows/release.yml@main
    with:
      generate: true
      attestations: true
  
  # 只发布到 PyPI
  pypi:
    uses: tree-sitter/workflows/.github/workflows/package-pypi.yml@main
    secrets:
      PYPI_API_TOKEN: ${{secrets.PYPI_API_TOKEN}}
    with:
      generate: true
  
  # NPM 发布 (暂时禁用)
  # npm:
  #   uses: tree-sitter/workflows/.github/workflows/package-npm.yml@main
  #   secrets:
  #     NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  #   with:
  #     generate: true
  
  # Crates.io 发布 (暂时禁用)
  # crates:
  #   uses: tree-sitter/workflows/.github/workflows/package-crates.yml@main
  #   secrets:
  #     CARGO_REGISTRY_TOKEN: ${{secrets.CARGO_REGISTRY_TOKEN}}
  #   with:
  #     generate: true
